name: Algorithm Code Style Check

# 仅在MR操作时触发
on: [pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy  # 安装核心工具

      - name: Check code format with Clang Format
        run: |
          echo "Running clang-format check..."
          # 查找所有C++源文件（可根据实际路径调整）
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.c++" | while read file; do
            echo "Checking format for $file"
            # 检查格式，--dry-run只报告不修改，-Werror将警告转为错误
            # 使用 --verbose 显示详细信息
            if ! clang-format --dry-run --Werror --style=file "$file"; then
              echo "ERROR: Format check failed for $file"
              echo "To fix, run: clang-format -i --style=file $file"
              echo "Format differences:"
              clang-format --style=file "$file" | diff -u "$file" -
              exit 1
            fi
          done
          echo "Clang-format check passed for all files"